### ISSUE TITLE
[Error] ERROR:  value "1672295751103" is out of range for type integer

### ISSUE THREAD

**Issue by Sakhalinfox** [Cameri/nostream#110]
**Describe the bug**
Viewing logs on attached tmux on Nostream v1.14.0 I see the following error: 

>ERROR:  value "1672295751103" is out of range for type integer
db              | 2022-12-29 06:36:05.620 UTC [153356] ERROR:  value "1672295751103" is out of range for type integer                                                                         
db              | 2022-12-29 06:36:05.620 UTC [153356] CONTEXT:  portal "C_75670" parameter $2 = '...'                                                                                        
db              | 2022-12-29 06:36:05.620 UTC [153356] STATEMENT:  select * from "events" where "event_kind" in ($1) and "event_created_at" >= $2 order by "event_created_at" asc 

**To Reproduce**
Not sure of the steps to reproduce but I wanted to report it for reference/documentation purpose. 

**Screenshots**
![image](https://user-images.githubusercontent.com/121224529/209915241-eb0cb43a-4f89-4a2b-9e19-ba00ebbadca5.png)
![image](https://user-images.githubusercontent.com/121224529/209915280-b61261e4-f8d5-4fc5-bb31-63c9067f8614.png)

**System (please complete the following information):**
 - OS: Ubuntu
 - Platform: Docker
 - Version: 1.14.0

**Logs**
>db              | 2022-12-29 06:36:05.620 UTC [153356] ERROR:  value "1672295751103" is out of range for type integer                                                                         
db              | 2022-12-29 06:36:05.620 UTC [153356] CONTEXT:  portal "C_75670" parameter $2 = '...'                                                                                        
db              | 2022-12-29 06:36:05.620 UTC [153356] STATEMENT:  select * from "events" where "event_kind" in ($1) and "event_created_at" >= $2 order by "event_created_at" asc             
nostr-ts-relay  | unable to handle message error: value "1672295751103" is out of range for type integer                                                                                      
nostr-ts-relay  |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)                                                                                       
nostr-ts-relay  |     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)                                                                                            
nostr-ts-relay  |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)                                                                                                    
nostr-ts-relay  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)                                                                                               
nostr-ts-relay  |     at Socket.emit (node:events:513:28)                                                                                                                                     
nostr-ts-relay  |     at addChunk (node:internal/streams/readable:324:12)                                                                                                                     
nostr-ts-relay  |     at readableAddChunk (node:internal/streams/readable:297:9)                                                                                                              
nostr-ts-relay  |     at Readable.push (node:internal/streams/readable:234:10)                                                                                                                
nostr-ts-relay  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {                                                                                                        
nostr-ts-relay  |   length: 153,                                                                                                                                                              
nostr-ts-relay  |   severity: 'ERROR',                                                                                                                                                        
nostr-ts-relay  |   code: '22003',                                                                                                                                                            
nostr-ts-relay  |   detail: undefined,                                                                                                                                                        
nostr-ts-relay  |   hint: undefined,                                                                                                                                                          
nostr-ts-relay  |   position: undefined,                                                                                                                                                      
nostr-ts-relay  |   internalPosition: undefined,                                                                                                                                              
nostr-ts-relay  |   internalQuery: undefined,                                                                                                                                                 
nostr-ts-relay  |   where: `portal "C_75670" parameter $2 = '...'`,                                                                                                                           
nostr-ts-relay  |   schema: undefined,                                                                                                                                                        
nostr-ts-relay  |   table: undefined,                                                                                                                                                         
nostr-ts-relay  |   column: undefined,                                                                                                                                                        
nostr-ts-relay  |   dataType: undefined,                                                                                                                                                      
nostr-ts-relay  |   constraint: undefined,                                                                                                                                                    
nostr-ts-relay  |   file: 'numutils.c',                                                                                                                                                       
nostr-ts-relay  |   line: '226',                      
nostr-ts-relay  |   routine: 'pg_strtoint32'                                                                                                                                                  
nostr-ts-relay  | }                                                                                                                                                                           
db              | 2022-12-29 06:37:51.686 UTC [27] LOG:  checkpoint starting: time                                                                                                            
db              | 2022-12-29 06:37:55.416 UTC [27] LOG:  checkpoint complete: wrote 38 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.720 s, sync=0.003 s, total=3.731 s;
 sync files=11, longest=0.002 s, average=0.001 s; distance=205 kB, estimate=322 kB                                                                                                            
db              | 2022-12-29 06:39:30.395 UTC [176656] ERROR:  value "1672281570251" is out of range for type integer                                                                         
db              | 2022-12-29 06:39:30.395 UTC [176656] CONTEXT:  portal "C_76081" parameter $2 = '...'                                                                                        
db              | 2022-12-29 06:39:30.395 UTC [176656] STATEMENT:  select * from "events" where "event_kind" in ($1) and "event_created_at" >= $2 order by "event_created_at" asc             
nostr-ts-relay  | unable to handle message error: value "1672281570251" is out of range for type integer                                                                                      
nostr-ts-relay  |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)                                                                                       
nostr-ts-relay  |     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)                                                                                            
nostr-ts-relay  |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)                                                                                                    
nostr-ts-relay  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)                                                                                               
nostr-ts-relay  |     at Socket.emit (node:events:513:28)                                                                                                                                     
nostr-ts-relay  |     at addChunk (node:internal/streams/readable:324:12)                                                                                                                     
nostr-ts-relay  |     at readableAddChunk (node:internal/streams/readable:297:9)                                                                                                              
nostr-ts-relay  |     at Readable.push (node:internal/streams/readable:234:10)                                                                                                                
nostr-ts-relay  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {                                                                                                        
nostr-ts-relay  |   length: 153,                                                                                                                                                              
nostr-ts-relay  |   severity: 'ERROR',                                                                                                                                                        
nostr-ts-relay  |   code: '22003',                                                                                                                                                            
nostr-ts-relay  |   detail: undefined,                                                                                                                                                        
nostr-ts-relay  |   hint: undefined,                                                                                                                                                          
nostr-ts-relay  |   position: undefined,                                                                                                                                                      
nostr-ts-relay  |   internalPosition: undefined,                                                                                                                                              
nostr-ts-relay  |   internalQuery: undefined,                                                                                                                                                 
nostr-ts-relay  |   where: `portal "C_76081" parameter $2 = '...'`,                                                                                                                           
nostr-ts-relay  |   schema: undefined,                                                                                                                                                        
nostr-ts-relay  |   table: undefined,                                                                                                                                                         
nostr-ts-relay  |   column: undefined,                                                                                                                                                        
nostr-ts-relay  |   dataType: undefined,                                                                                                                                                      
nostr-ts-relay  |   constraint: undefined,                                                                                                                                                    
nostr-ts-relay  |   file: 'numutils.c',                                                                                                                                                       
nostr-ts-relay  |   line: '226',                                                                                                                                                              
nostr-ts-relay  |   routine: 'pg_strtoint32'                                                                                                                                                  
nostr-ts-relay  | }                                                                                                                                                                           
db              | 2022-12-29 06:42:51.466 UTC [27] LOG:  checkpoint starting: time

**Comment by Cameri** [comment]
Thanks for the report @Sakhalinfox !
