### ISSUE TITLE
[Error] TypeError: Cannot read properties of undefined (reading '__knexUid') 

### ISSUE THREAD

**Issue by Sakhalinfox** [Cameri/nostream#111]
**Describe the bug**

- Did git pull origin main to update from version 1.14.0 to 1.15.0 from git main branch.
- Stopped Docker container gracefully.
- Restarted with command "npm run docker:compose:start"
- Docker container started and below Nostream ASCII text v1.15.0 I see the error 
>nostr-ts-relay  |                               v1.15.0 by Cameri                                                                                                                             
nostr-ts-relay  |             NIPs implemented: 1,2,4,9,11,12,15,16,20,22,26,28,33                                                                                                            
nostr-ts-relay  |                               4 workers started                                                                                                                             
nostr-ts-relay  | /app/src/app/worker.js:29                                                                                                                                                   
nostr-ts-relay  |         throw error;                                                                                                                                                        
nostr-ts-relay  |         ^                                                                                                                                                                   
nostr-ts-relay  |                                                                                                                                                                             
nostr-ts-relay  | TypeError: Cannot read properties of undefined (reading '__knexUid')                                                                                                        
nostr-ts-relay  |     at Client_PG.releaseConnection (/app/node_modules/knex/lib/client.js:319:58)                                                                                            
nostr-ts-relay  |     at Transform.<anonymous> (/app/node_modules/knex/lib/execution/runner.js:72:19)                                                                                         
nostr-ts-relay  |     at Transform.emit (node:events:525:35)                                                                                                                                  
nostr-ts-relay  |     at emitCloseNT (node:internal/streams/destroy:132:10)                                                                                                                   
nostr-ts-relay  |     at emitErrorCloseNT (node:internal/streams/destroy:117:3)                                                                                                               
nostr-ts-relay  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)                                                                                          
nostr-ts-relay  |                                                                                                                                                                             
nostr-ts-relay  | Node.js v18.12.1                                                                                                                                                            
db              | 2022-12-29 07:06:44.318 UTC [108] LOG:  could not receive data from client: Connection reset by peer                                                                        
db              | 2022-12-29 07:11:05.943 UTC [27] LOG:  checkpoint starting: time                                                                                                            
db              | 2022-12-29 07:11:43.654 UTC [27] LOG:  checkpoint complete: wrote 380 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=37.702 s, sync=0.004 s, total=37.712
 s; sync files=26, longest=0.003 s, average=0.001 s; distance=1674 kB, estimate=1674 kB    

Errors keep showing up in the log often. 

**Screenshots**
![image](https://user-images.githubusercontent.com/121224529/209918227-f6f9d677-e358-4fbf-af13-3e3d37bae27e.png)

**System (please complete the following information):**
 - OS: Ubuntu
 - Platform: Docker
 - Version: 1.15.0

**Comment by Cameri** [comment]
I don't have enough information to reproduce this error.

**Comment by Sakhalinfox** [comment]
> I don't have enough information to reproduce this error.

Me neither. Feel free to close it for now as I don't see it anymore after updating to 1.15.1. If it comes up again I can create a new error report. Thanks!
