### ISSUE TITLE
[REQUEST] Add IP address blacklist option

### ISSUE THREAD

**Issue by Sakhalinfox** [Cameri/nostream#121]
I feel like the IP whitelist there will be many instances in which a relay operator would want to blacklist an IP or a range of IP addresses because of spam or any other abuse of service, apart from the pubkey blacklist. This isn't a definite answer to the spam problem, but it's a starting point. 

**Is your feature request related to a problem? Please describe.**
Ongoing spam problems.

**Describe the solution you'd like**
Add an option in settings.config for IP blacklist below where IP whitelists now sits and add the programming logic to handle this.

**Describe alternatives you've considered**
Need a mechanism to identify spam. Maybe relays identify repeated messages sent in a short span of time like about 15-20 notes every few seconds and auto block the IP and pubkey (either permanent or temporary as an option). I think once a Web relay management application exists, they can be placed in a log for approvals/rejections from the temporary (Short time) block queue to a permanent block.

**Comment by etemiz** [comment]
sudo ufw deny from {ip-address-here} to any ?

**Comment by Sakhalinfox** [comment]
> You may use firewall for this `sudo ufw deny from {ip-address-here} to any`

Thanks I think that works for my current usecase,

**Comment by etemiz** [comment]
Apparently my ufw was not doing its job for already established connections. 
So this is the way to ban an IP.

Add this line to /etc/ufw/before.rules:

`-A ufw-before-input -s 5.4.3.2 -j DROP`

It has to go above the line `# quickly process packets for which we already have a connection`.
