### ISSUE TITLE
[BUG] NIP-09 kind=5 'Deletion' bug

### ISSUE THREAD

**Issue by bondedcto** [Cameri/nostream#129]
Cameri advises for this to be raised as a bug.

kind=5 delete event issues 

I have an event (1) 
for which I've created a deletion event kind=5 (2) 
then I query nostr (nostream) using the event_id from 1 (3)
yet I the nostream relay still returns the event (4)

My understanding is that the relay must refrain from disseminating the event in (4) given there is a deletion event for it.

=== (1) event I want to delete
we got the event we wanted: {
  id: 'e79f31b545f006087f7bd27d9febeb71ae6945424d1f0b5db3958099da0d59a3',
  kind: 1,
  pubkey: '2b78a7d19a411e800cfa86fd0e72aaa0652981b1d5b33a0c445050d06ad8c1ee',
  created_at: 1673342359,
  content: 'hi',
  tags: [ [ 'y', '333' ], [ 'x', '333' ], [ 'tagTagTag' ] ],
...
...
}

=== (2) kind=5 deletion event
publish is being run
{
  kind: 5,
  pubkey: '2b78a7d19a411e800cfa86fd0e72aaa0652981b1d5b33a0c445050d06ad8c1ee',
  created_at: 1673342504,
  tags: [
    [
      'e',
      'e79f31b545f006087f7bd27d9febeb71ae6945424d1f0b5db3958099da0d59a3'
    ]
  ],
  content: 'hi',
  id: '8940ae287b86176b9214b3ef4e77c66d9d19d1a266445ca9f5ca71c2d4f17ad4',
...
...

=== (3) subsequent query for the event in (1)
    let sub = relay.sub([
      {
        ids: ['e79f31b545f006087f7bd27d9febeb71ae6945424d1f0b5db3958099da0d59a3']
      }
    ])

=== (4) and I still receive the event  :what-have-i-done-wrong-face
we got the event we wanted: {
  id: 'e79f31b545f006087f7bd27d9febeb71ae6945424d1f0b5db3958099da0d59a3',
  kind: 1,
  pubkey: '2b78a7d19a411e800cfa86fd0e72aaa0652981b1d5b33a0c445050d06ad8c1ee',
  created_at: 1673342359,
  content: 'hi',
  tags: [ [ 'y', '333' ], [ 'x', '333' ], [ 'tagTagTag' ] ],
  ...
...

**System (please complete the following information):**
 - OS: Ubuntu client
 - Platform: railway relay
 - Version:  [c439dc8](https://github.com/Cameri/nostream/commit/c439dc85dfbac3ae23a45c1989da1fc35617bc49)

**Comment by Cameri** [comment]
Looking into this now.
