### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading '__knexUid')

### ISSUE THREAD

**Issue by Giszmo** [Cameri/nostream#140]
I suspect that some bug is causing bulk connection drops.

In a long list of `LOG: unexpeced EOF on client` ... I see this error twice:

```
nostr-ts-relay  | /app/src/app/worker.js:29
nostr-ts-relay  |         throw error;
nostr-ts-relay  |         ^
nostr-ts-relay  | 
nostr-ts-relay  | TypeError: Cannot read properties of undefined (reading '__knexUid')
nostr-ts-relay  |     at Client_PG.releaseConnection (/app/node_modules/knex/lib/client.js:324:58)
nostr-ts-relay  |     at Transform.<anonymous> (/app/node_modules/knex/lib/execution/runner.js:72:19)
nostr-ts-relay  |     at Transform.emit (node:events:525:35)
nostr-ts-relay  |     at emitCloseNT (node:internal/streams/destroy:132:10)
nostr-ts-relay  |     at emitErrorCloseNT (node:internal/streams/destroy:117:3)
nostr-ts-relay  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
nostr-ts-relay  |     at runNextTicks (node:internal/process/task_queues:64:3)
nostr-ts-relay  |     at listOnTimeout (node:internal/timers:533:9)
nostr-ts-relay  |     at process.processTimers (node:internal/timers:507:7)
nostr-ts-relay  | 
nostr-ts-relay  | Node.js v18.12.1
```

I think 50 of 400 clients dropped that moment.

I'm running rev 273dcc65303b9fef9b974715cd65932cb6fd8c6f.

(sorry for not going through the template.)

**Comment by Giszmo** [comment]
I'm getting this slightly different stacktrace now at startup.

```
nostr-ts-relay        |                                                                                               
nostr-ts-relay        |  ███▄    █  ▒█████    ██████ ▄▄▄█████▓ ██▀███  ▓█████ ▄▄▄       ███▄ ▄███▓                    
nostr-ts-relay        |  ██ ▀█   █ ▒██▒  ██▒▒██    ▒ ▓  ██▒ ▓▒▓██ ▒ ██▒▓█   ▀▒████▄    ▓██▒▀█▀ ██▒                    
nostr-ts-relay        | ▓██  ▀█ ██▒▒██░  ██▒░ ▓██▄   ▒ ▓██░ ▒░▓██ ░▄█ ▒▒███  ▒██  ▀█▄  ▓██    ▓██░                    
nostr-ts-relay        | ▓██▒  ▐▌██▒▒██   ██░  ▒   ██▒░ ▓██▓ ░ ▒██▀▀█▄  ▒▓█  ▄░██▄▄▄▄██ ▒██    ▒██                     
nostr-ts-relay        | ▒██░   ▓██░░ ████▓▒░▒██████▒▒  ▒██▒ ░ ░██▓ ▒██▒░▒████▒▓█   ▓██▒▒██▒   ░██▒                    
nostr-ts-relay        | ░ ▒░   ▒ ▒ ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░  ▒ ░░   ░ ▒▓ ░▒▓░░░ ▒░ ░▒▒   ▓▒█░░ ▒░   ░  ░                    
nostr-ts-relay        | ░ ░░   ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░    ░      ░▒ ░ ▒░ ░ ░  ░ ▒   ▒▒ ░░  ░      ░                    
nostr-ts-relay        |    ░   ░ ░ ░ ░ ░ ▒  ░  ░  ░    ░        ░░   ░    ░    ░   ▒   ░      ░                       
nostr-ts-relay        |          ░     ░ ░        ░              ░        ░  ░     ░  ░       ░                       
nostr-ts-relay        |                               v1.17.0 by Cameri                                               
nostr-ts-relay        |             NIPs implemented: 1,2,4,9,11,12,15,16,20,22,26,28,33
nostr-ts-relay        |                               8 workers started
nostream-tor_proxy-1  | Jan 16 17:02:15.000 [notice] New control connection opened from 10.10.10.2.
nostr-ts-relay        | saving private key to /home/node/v3_onion_private_key
nostr-ts-relay        | tor hidden service address: o3kbnz7kax2evrlbro3ixuo7ddlgi6ijg3uifwdpuha5gsgenannikad.onion:80
nostr-ts-relay        | /app/src/app/worker.js:29
nostr-ts-relay        |         throw error;
nostr-ts-relay        |         ^
nostr-ts-relay        | 
nostr-ts-relay        | TypeError: Cannot read properties of undefined (reading '__knexUid')
nostr-ts-relay        |     at Client_PG.releaseConnection (/app/node_modules/knex/lib/client.js:324:58)
nostr-ts-relay        |     at Transform.<anonymous> (/app/node_modules/knex/lib/execution/runner.js:72:19)
nostr-ts-relay        |     at Transform.emit (node:events:525:35)
nostr-ts-relay        |     at emitCloseNT (node:internal/streams/destroy:132:10)
nostr-ts-relay        |     at emitErrorCloseNT (node:internal/streams/destroy:117:3)
nostr-ts-relay        |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
nostr-ts-relay        | 
nostr-ts-relay        | Node.js v18.12.1
```

After restarting 2h ago, it apparently did not come up well but with no other errors I could see.

I changed postgres, nginx and nostream configs to allow for more client connections as discussed on TG. The server's disk IO dropped dramatically, while `ss -s` reporting record connections. Restarting the relay 2h ago then appears to have killed it. Now, after a new restart, where I saw above error again it appear to be accepting connections.

I noticed that it responded slowly on the first try but now it looks good. By "slowly" I mean that [querying 500 events](https://nostr.info/relays/) yielded 1 event quickly and only after several seconds did it pick up speed, delivering the other 499.

**Comment by Cameri** [comment]
> I noticed that it responded slowly on the first try but now it looks good. By "slowly" I mean that [querying 500 events](https://nostr.info/relays/) yielded 1 event quickly and only after several seconds did it pick up speed, delivering the other 499.
If you didn't limit your query to historical events it's possible that first event that came in was just recently broadcasted. Nostream doesn't wait for the stored events to be sent first before sending you recently broadcasted ones.

**Comment by Giszmo** [comment]
> If you didn't limit your query to historical events it's possible that first event that came in was just recently broadcasted. Nostream doesn't wait for the stored events to be sent first before sending you recently broadcasted ones.

That is a super interesting bit of information I guess most client devs are not aware of. My relay implementation probably has the same property there. That probably also is prone to deliver events twice and out of order.

**Comment by Cameri** [comment]
> > If you didn't limit your query to historical events it's possible that first event that came in was just recently broadcasted. Nostream doesn't wait for the stored events to be sent first before sending you recently broadcasted ones.
> 
> 
> 
> That is a super interesting bit of information I guess most client devs are not aware of. My relay implementation probably has the same property there. That probably also is prone to deliver events twice and out of order.

Do you think the relay should buffer those and wait for EOSE?

**Comment by Giszmo** [comment]
I think it's a curiosity I had not thought about before but it's not very consequential.

I thought there was some prescription of the sorting of results but I can't find it now. Wasn't there something about events sorted newest to oldest if limit provided but oldest to newest else? Might have been removed because of what we are talking about here. Anyway, the nips don't mandate it one way or the other and clients shouldn't be surprised if they get some few duplicate events.
