### ISSUE TITLE
Unable to acquire connection

### ISSUE THREAD

**Issue by bleetube** [Cameri/nostream#145]
I seem to be hitting a regression on v1.17.2, possibly related to #143.

On startup, the relay will process requests anywhere from a minute to an hour, after which point the relay stalls and spams the log with this error:   `Unable to acquire connection. Please increase DB_MAX_POOL_SIZE, DB_ACQUIRE_CONNECTION_TIMEOUT and tune postgresql.conf to make use of server's resources.`

Over the course of today I've tried to tune pool size, ultimately to no effect. No matter what I do, after about an hour (or less) all of the workers stall out and the relay stops responding to clients altogether.

When I look at the `pg_stat_activity` table, all of the pool sessions are still open. I'm using `watch "uptime && psql nostream -c 'select datid,datname,pid,usename,age(now(),query_start),state_change,wait_event_type,wait_event,state,backend_xid,backend_xmin,backend_type from pg_stat_activity;'"`

Rolling back to v1.16.0 appears to resolve the issue.

 - OS: Ubuntu 22.04
 - Platform: docker 20.10.22
 - ts-relay Version: 1.17.2
 - Postgresql 13.9-1, and 14.6-1

Happy to attach more debug logs if it helps. I can just roll forward again for a bit.

**Comment by Sakhalinfox** [comment]
I'm facing the same issue. I used [PGtune](https://pgtune.leopard.in.ua/) to configure postgresql.conf and also increased the DB_MAX_POOL_SIZE in docker-compose.yml (max connections divided by number of cpu or workers) , but eventually after a few hours it comes back up. I'm running v1.18.0 in Docker.

`nostr-ts-relay  | Unable to acquire connection. Please increase DB_MAX_POOL_SIZE,
DB_ACQUIRE_CONNECTION_TIMEOUT and tune postgresql.conf to make use of server's resources.`

**Comment by bleetube** [comment]
@Sakhalinfox  Looks like upgrading to Postgres 14 solves this issue. Let me know if that helps your case and I will close this issue.

**Comment by bleetube** [comment]
I've been running v1.19.0 for a few hours now and haven't seen this issue recur yet. @Sakhalinfox can you try upgrading and see if that solves this? If so, we can close out this issue.

**Comment by Cameri** [comment]
Fixed in #130

**Comment by Sakhalinfox** [comment]
> I've been running v1.19.0 for a few hours now and haven't seen this issue recur yet. @Sakhalinfox can you try upgrading and see if that solves this? If so, we can close out this issue.

Thanks, I noticed the same and it was resolved for me too.
