### ISSUE TITLE
[REQUEST] Add support to optionally use connection uri for postgresql and redis

### ISSUE THREAD

**Issue by fastfists** [Cameri/nostream#151]
Ran into an issue where redis and postgresql database provider required ssl to be turned on in order to accept requests. Ended up having to manually edit the query string to enable ssl support.

**Comment by fastfists** [comment]
I already have a pr for this can I go ahead and submit it?

**Comment by kmkhami** [comment]
I think this feature is beneficial for the user-experience as well. If using a database provider, it is typically easier to use a connection `URI` instead of individual params.

**Comment by Cameri** [comment]
Please submit a PR :)

**Comment by kmkhami** [comment]
Added as #154 , thanks!

**Comment by Cameri** [comment]
Merged
