### ISSUE TITLE
[BUG] v1.19 expects settings.json even though it is not required.

### ISSUE THREAD

**Issue by arunned** [Cameri/nostream#157]
**Describe the bug**

v1.19 swiches to settings.yaml file to load settings. however, if the settings.json file is not found, then it gives an error when starting. 
from log file

Feb 02 22:12:06 ip-172-31-31-228 node[2759]: Error: ENOENT: no such file or directory, watch '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json'
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Object.watch (node:fs:2304:36)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at SettingsStatic.watchSettings (/home/ubuntu/nostream-1.19.0/dist/src/utils/settings.js:104:26)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at App.run (/home/ubuntu/nostream-1.19.0/dist/src/app/app.js:34:51)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Object.<anonymous> (/home/ubuntu/nostream-1.19.0/dist/src/index.js:33:30)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Module._compile (node:internal/modules/cjs/loader:1239:14)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Module.load (node:internal/modules/cjs/loader:1096:32)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Module._load (node:internal/modules/cjs/loader:935:12)
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12) {
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:   errno: -2,
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:   syscall: 'watch',
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:   code: 'ENOENT',
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:   path: '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json',
Feb 02 22:12:06 ip-172-31-31-228 node[2759]:   filename: '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json'
Feb 02 22:12:06 ip-172-31-31-228 node[2759]: }
Feb 02 22:12:06 ip-172-31-31-228 node[2759]: Node.js v19.4.0
Feb 02 22:12:06 ip-172-31-31-228 systemd[1]: nostr.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 22:12:06 ip-172-31-31-228 systemd[1]: nostr.service: Failed with result 'exit-code'.
Feb 02 22:12:06 ip-172-31-31-228 systemd[1]: nostr.service: Consumed 1.648s CPU time.
Feb 02 22:12:11 ip-172-31-31-228 systemd[1]: nostr.service: Scheduled restart job, restart counter is at 1.
Feb 02 22:12:11 ip-172-31-31-228 systemd[1]: Stopped NOSTR relay  daemon.
Feb 02 22:12:11 ip-172-31-31-228 systemd[1]: nostr.service: Consumed 1.648s CPU time.
Feb 02 22:12:11 ip-172-31-31-228 systemd[1]: Started NOSTR relay  daemon.
Feb 02 22:12:13 ip-172-31-31-228 node[2769]: 2023-02-02T22:12:13.134Z primary:app-primary starting
Feb 02 22:12:13 ip-172-31-31-228 node[2769]: 2023-02-02T22:12:13.137Z primary:app-primary started
Feb 02 22:12:13 ip-172-31-31-228 node[2769]: node:internal/fs/watchers:255
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     throw error;
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     ^
Feb 02 22:12:13 ip-172-31-31-228 node[2769]: Error: ENOENT: no such file or directory, watch '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json'
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Object.watch (node:fs:2304:36)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at SettingsStatic.watchSettings (/home/ubuntu/nostream-1.19.0/dist/src/utils/settings.js:104:26)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at App.run (/home/ubuntu/nostream-1.19.0/dist/src/app/app.js:34:51)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Object.<anonymous> (/home/ubuntu/nostream-1.19.0/dist/src/index.js:33:30)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Module._compile (node:internal/modules/cjs/loader:1239:14)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Module.load (node:internal/modules/cjs/loader:1096:32)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Module._load (node:internal/modules/cjs/loader:935:12)
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12) {
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:   errno: -2,
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:   syscall: 'watch',
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:   code: 'ENOENT',
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:   path: '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json',
Feb 02 22:12:13 ip-172-31-31-228 node[2769]:   filename: '/home/ubuntu/nostream-1.19.0/dist/src/.nostr/settings.json'
Feb 02 22:12:13 ip-172-31-31-228 node[2769]: }

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Platform: [e.g. docker, standalone]
 - Version: [e.g. 1.9.11]

**Logs**
If applicable, attach log messages showing the bug and context when the bug happened.

**Additional context**

**Comment by nohea** [comment]
confirmed. I got the error on a new install. 
After i did:
```
touch .nostr/settings.json
npm run dev
```
... it started up

**Comment by nohea** [comment]
never mind - i found the problem in src/utils/settings.ts
it has to be settings.yaml , not .yml

if i renamed the file, it runs

**Comment by antonleviathan** [comment]
This [PR](https://github.com/Cameri/nostream/pull/158/files) fixes this. If the issue persists please let us know.
