### ISSUE TITLE
[BUG] ENOENT settings.undefined

### ISSUE THREAD

**Issue by AbelLykens** [Cameri/nostream#159]
**Describe the bug**
When installing from scratch I get:
Error: ENOENT: no such file or directory, watch '/opt/nostr/dist/.nostr/settings.undefined'

If/once I `touch` the fie `npm run start` does work

**To Reproduce**
1. Clean install on debian 11
2. Try npm run dev

**Expected behavior**
Nostream starts

**Screenshots**
`Error: ENOENT: no such file or directory, watch '/opt/nostr/dist/.nostr/settings.undefined'`

**System (please complete the following information):**
 - OS: Debian 1
 - Platform: Standalone
 - Version: master @ [1475d65](https://github.com/Cameri/nostream/commit/1475d65b41416cac8a53a9f7ed73d45e830ac50e)

**Logs**
If applicable, attach log messages showing the bug and context when the bug happened.

**Additional context**

**Comment by moeabdol** [comment]
I can confirm this happening when running locally using `./scripts/start_local`

**Comment by antonleviathan** [comment]
This [PR](https://github.com/Cameri/nostream/pull/158/files) fixes this. Please let us know if the issue persists for you!

**Comment by AbelLykens** [comment]
Thank you @antonleviathan , I am happily running nostream now so will not test if this is fixed on a new install, sorry.
