### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by mdavids** [Cameri/nostream#167]
Shouldn't it say 'content-type' instead of 'conten-type' ?

https://github.com/Cameri/nostream/blob/67ad1eb1d15b570c42343a1a92a2d142110cced4/src/handlers/request-handlers/root-request-handler.ts#L26

**Comment by SarthakSanjay** [comment]
I would like to work on this issue please assign me.

**Comment by Cameri** [comment]
@SarthakSanjay go for it!

**Comment by antonleviathan** [comment]
Thank you for pointing this out @mdavids

**Comment by Cameri** [comment]
This was fixed at some point.
