### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MarkDarwin** [Cameri/nostream#178]
**Describe the bug**
Whitelisting pubkeys in .nostr/settings.yml doesn't appear to be working. I get asked for payment again when visiting the relay's site - [https://private.red.gb.net](https://private.red.gb.net)

**To Reproduce**
1. Visit https://damus.io/key/
2. Paste my npub key and copy the hex key output
1. nano .nostr/settings.yml
3. Replace in two sections, 'info/pubkey' and 'payments/feeSchedules/admission/whiltelists/pubkeys'  'replace-with-your-pubkey-in-hex' with the new hex key
4. stop and start docker
5. visit https://private.red.gb.net

**Expected behavior**
I expected to not be presented with another invoice for payment
Instead, I was hoping it would show a note saying payment already received

**Screenshots**
[image](https://nostr.build/i/nostr.build_6bdfe1a95b3acef5370219fd6a80120629ddb7bd43b6dca5e0f656c55b9e9be0.png)

**System (please complete the following information):**
 - OS: ubuntu 2204 minimal
 - Platform: docker
 - Version: 23.0.0, build e92dd87

**Logs**
Don't have logs but happy to find some if shown which commands to run

**Additional context**
This is a new setup so perhaps I'm not understanding the workflow. If so, apologies

**Comment by MarkDarwin** [comment]
After more testing, which I should have done before so sorry about that:

If I proceed past the payment request, this is shown in the browser:
No admission fee required

I then tested this on another relay which I'd paid for and was shown this in the browser:
User is already admitted.

It looks like it is working as designed so feel free to close this as it's not a bug.

It might however be a better end user experience if you could be shown this before committing to potentially paying again.

**Comment by Cameri** [comment]
Glad you were able to figure this one out! We'll definitely look into improving the experience.
