### ISSUE TITLE
[BUG] execute start script error

### ISSUE THREAD

**Issue by BaLaLaLs** [Cameri/nostream#183]
**Describe the bug**

**To Reproduce**
1. Run command ./scripts/start
2. See error
[stage-1 3/6] RUN apk add --no-cache --update git:                                                                                                                                                                                                  
#0 3.769 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz                                                                                                                                                                 
#0 8.776 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: temporary error (try again later)                                                                                                                                         
#0 8.777 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz                                                                                                                                                            
#0 13.79 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: temporary error (try again later)                                                                                                                                    
#0 13.79   git (no such package):
#0 13.79     required by: world[git]
#0 13.79 ERROR: unable to select packages:

**System (please complete the following information):**
 - OS: CentOS-7.0.1406-x64
Docker version 23.0.0, build e92dd87

[nostream@C20230207177167 nostream]$ wget https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz > /dev/null
--2023-02-08 00:26:52--  https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
正在解析主机 dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)... 151.101.2.133, 151.101.66.133, 151.101.130.133, ...
正在连接 dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)|151.101.2.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：1809677 (1.7M) [application/octet-stream]
正在保存至: “APKINDEX.tar.gz.1”

30% [=============================================================>                                                                                                                                                ] 548,864      113KB/s 
curl is work good.

**Comment by antonleviathan** [comment]
Hi @BaLaLaLs, is it possible for you to use Ubuntu22.10 instead of CentosOS? You can refer to [this guide](https://andreneves.xyz/p/set-up-a-nostr-relay-server-in-under) if you aren't following it at the moment. The issue you are experiencing stems from package incompatibility across CentosOS (based on RedHat) vs Ubuntu (based on Debian).

**Comment by BaLaLaLs** [comment]
@antonleviathan I changed to ubuntu, which really solved my problem. But I want to say that Centos is one of the most common server systems. It would be better to support it.
