### ISSUE TITLE
[BUG]  FATAL:  could not map anonymous shared memory: Cannot allocate memory

### ISSUE THREAD

**Issue by pluja** [Cameri/nostream#189]
**Describe the bug**
Can not start Nostream due to not enough memory.

**To Reproduce**
Run nostream on a small vps (2GB RAM)

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Debian
 - Platform: docker
 - Version: latest

**Logs**

```
nostream-db       | 2023-02-10 12:18:43.673 UTC [1] FATAL:  could not map anonymous shared memory: Cannot allocate memory
nostream-db       | 2023-02-10 12:18:43.673 UTC [1] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap space, or huge pages. To reduce the request size (currently 4438917120 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
```

**Additional context**
Is there a way to solve this or are there special memory requirements for Nostream to work?

**Comment by Cameri** [comment]
Stop your relay using `./scripts/stop`.
Delete your `.nostr/data` folder, then edit your postgresql.conf file using the values https://pgtune.leopard.in.ua/
Use OTP for DB Type.

**Comment by pluja** [comment]
Thanks!
