### ISSUE TITLE
[BUG] Please configure the secret using the SECRET environment variable

### ISSUE THREAD

**Issue by zyhhhy** [Cameri/nostream#217]
**Describe the bug**
I want to deploy nostream on a server. Nostream always notice that "Please configure the secret using the SECRET environment variable" and cannot start the service.

**To Reproduce**
1. Run command './scripts/start'

**System (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Platform: docker
 - Version: 
Docker version 23.0.1, build a5ee5b1
node v12.22.9
nostream latest

**Logs**
Attaching to nostream, nostream-cache, nostream-db, nostream-migrate
nostream-cache    | 1:C 19 Feb 2023 00:56:32.841 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
nostream-cache    | 1:C 19 Feb 2023 00:56:32.841 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
nostream-cache    | 1:C 19 Feb 2023 00:56:32.841 # Configuration loaded
nostream-cache    | 1:M 19 Feb 2023 00:56:32.842 # Server initialized
nostream-cache    | 1:M 19 Feb 2023 00:56:32.842 # WARNING Your system is configured to use the 'xen' clocksource which might lead to degraded performance. Check the result of the [slow-clocksource] system check: run 'redis-server --check-system' to check if the system's clocksource isn't degrading performance.
nostream-db       | The files belonging to this database system will be owned by user "postgres".
nostream-db       | This user must also own the server process.
nostream-db       | 
nostream-db       | The database cluster will be initialized with locale "en_US.utf8".
nostream-db       | The default database encoding has accordingly been set to "UTF8".
nostream-db       | The default text search configuration will be set to "english".
nostream-db       | 
nostream-db       | Data page checksums are disabled.
nostream-db       | 
nostream-db       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
nostream-db       | creating subdirectories ... ok
nostream-db       | selecting dynamic shared memory implementation ... posix
nostream-db       | selecting default max_connections ... 100
nostream-db       | selecting default shared_buffers ... 128MB
nostream-db       | selecting default time zone ... Etc/UTC
nostream-db       | creating configuration files ... ok
nostream-db       | running bootstrap script ... ok
nostream-db       | performing post-bootstrap initialization ... ok
nostream-db       | syncing data to disk ... ok
nostream-db       | 
nostream-db       | 
nostream-db       | Success. You can now start the database server using:
nostream-db       | 
nostream-db       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
nostream-db       | 
nostream-db       | initdb: warning: enabling "trust" authentication for local connections
nostream-db       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
nostream-db       | waiting for server to start....2023-02-19 00:56:33.943 UTC [48] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
nostream-db       | 2023-02-19 00:56:33.947 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
nostream-db       | 2023-02-19 00:56:33.961 UTC [51] LOG:  database system was shut down at 2023-02-19 00:56:33 UTC
nostream-db       | 2023-02-19 00:56:33.972 UTC [48] LOG:  database system is ready to accept connections
nostream-db       |  done
nostream-db       | server started
nostream-db       | CREATE DATABASE
nostream-db       | 
nostream-db       | 
nostream-db       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
nostream-db       | 
nostream-db       | 2023-02-19 00:56:34.158 UTC [48] LOG:  received fast shutdown request
nostream-db       | waiting for server to shut down....2023-02-19 00:56:34.163 UTC [48] LOG:  aborting any active transactions
nostream-db       | 2023-02-19 00:56:34.165 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
nostream-db       | 2023-02-19 00:56:34.166 UTC [49] LOG:  shutting down
nostream-db       | 2023-02-19 00:56:34.170 UTC [49] LOG:  checkpoint starting: shutdown immediate
nostream-db       | 2023-02-19 00:56:34.319 UTC [49] LOG:  checkpoint complete: wrote 918 buffers (0.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.105 s, sync=0.030 s, total=0.153 s; sync files=250, longest=0.022 s, average=0.001 s; distance=4217 kB, estimate=4217 kB
nostream-db       | 2023-02-19 00:56:34.331 UTC [48] LOG:  database system is shut down
nostream-db       |  done
nostream-db       | server stopped
nostream-db       | 
nostream-db       | PostgreSQL init process complete; ready for start up.
nostream-db       | 
nostream-db       | 2023-02-19 00:56:34.418 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
nostream-db       | 2023-02-19 00:56:34.418 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
nostream-db       | 2023-02-19 00:56:34.418 UTC [1] LOG:  listening on IPv6 address "::", port 5432
nostream-db       | 2023-02-19 00:56:34.427 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
nostream-db       | 2023-02-19 00:56:34.438 UTC [64] LOG:  database system was shut down at 2023-02-19 00:56:34 UTC
nostream-db       | 2023-02-19 00:56:34.446 UTC [1] LOG:  database system is ready to accept connections
nostream-migrate  | 
nostream-migrate  | added 36 packages in 2s
nostream-migrate  | 
nostream-migrate  | 3 packages are looking for funding
nostream-migrate  |   run `npm fund` for details
nostream-migrate  | npm notice 
nostream-migrate  | npm notice New minor version of npm available! 9.3.1 -> 9.5.0
nostream-migrate  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.5.0>
nostream-migrate  | npm notice Run `npm install -g npm@9.5.0` to update!
nostream-migrate  | npm notice 
nostream-migrate  | Batch 1 run: 20 migrations
nostream-migrate exited with code 0
nostream          | 
nostream          |  ███▄    █  ▒█████    ██████ ▄▄▄█████▓ ██▀███  ▓█████ ▄▄▄       ███▄ ▄███▓
nostream          |  ██ ▀█   █ ▒██▒  ██▒▒██    ▒ ▓  ██▒ ▓▒▓██ ▒ ██▒▓█   ▀▒████▄    ▓██▒▀█▀ ██▒
nostream          | ▓██  ▀█ ██▒▒██░  ██▒░ ▓██▄   ▒ ▓██░ ▒░▓██ ░▄█ ▒▒███  ▒██  ▀█▄  ▓██    ▓██░
nostream          | ▓██▒  ▐▌██▒▒██   ██░  ▒   ██▒░ ▓██▓ ░ ▒██▀▀█▄  ▒▓█  ▄░██▄▄▄▄██ ▒██    ▒██
nostream          | ▒██░   ▓██░░ ████▓▒░▒██████▒▒  ▒██▒ ░ ░██▓ ▒██▒░▒████▒▓█   ▓██▒▒██▒   ░██▒
nostream          | ░ ▒░   ▒ ▒ ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░  ▒ ░░   ░ ▒▓ ░▒▓░░░ ▒░ ░▒▒   ▓▒█░░ ▒░   ░  ░
nostream          | ░ ░░   ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░    ░      ░▒ ░ ▒░ ░ ░  ░ ▒   ▒▒ ░░  ░      ░
nostream          |    ░   ░ ░ ░ ░ ░ ▒  ░  ░  ░    ░        ░░   ░    ░    ░   ▒   ░      ░
nostream          |          ░     ░ ░        ░              ░        ░  ░     ░  ░       ░
nostream          |                                   v1.22.4
nostream          |           NIPs implemented: 1,2,4,9,11,12,15,16,20,22,26,28,33,40
nostream          |                            Pay-to-relay disabled
nostream          |                          Payments provider: zebedee
nostream          | Please configure the secret using the SECRET environment variable.

**Comment by jilv220** [comment]
Don't use this commit. It is bugged.

**Comment by jilv220** [comment]
Just keep the previous version.

**Comment by zyhhhy** [comment]
@jilv220 Yes. It works. Thank you!

**Comment by okjodom** [comment]
@jilv220 , 

> Don't use this commit. It is bugged.

this bug is reproducible on latest. Please reactivate?

Also, if you have more context on what bugs there are on latest master, could you share details here?

I know the failing check was added in [this commit](https://github.com/Cameri/nostream/pull/194/commits/76c797b9b9322ee1b3c138d09f9ab0825d961f25#diff-1f3b8fd70c897aecce2091effdb165a24a2bcdf2f61407b90f0d05e90b7c5368) introduced by #194 

> Just keep using the previous release.

This is a non-tirvial suggestion especially after running migrations on previous release

**Comment by jilv220** [comment]
> @jilv220 ,
> 
> > Don't use this commit. It is bugged.
> 
> this bug is reproducible on latest. Please reactivate? @zyhhhy
> 
> Also, if you have more context on what bugs there are on latest master, could you share details here?
> 
> I know the failing check was added in [this commit](https://github.com/Cameri/nostream/pull/194/commits/76c797b9b9322ee1b3c138d09f9ab0825d961f25#diff-1f3b8fd70c897aecce2091effdb165a24a2bcdf2f61407b90f0d05e90b7c5368) introduced by #194
> 
> > Just keep using the previous release.
> 
> This is a non-tirvial suggestion especially after running migrations on previous release

You can connect the database and delete 'change_invoice_id' and 'scale_balance_addition' from the knex_migration table. This should let you revert the migration back to the previous version.

**Comment by jilv220** [comment]
I guess the issue is from https://github.com/Cameri/nostream/blob/2342386bb4f04ed2cac2b7eb4c1b9f0c5703b006/src/factories/maintenance-worker-factory.ts

I can start the local fine, but once I start the production, I no longer receive subscriptions from the client.
