### ISSUE TITLE
[BUG] Running start script within scripts folder causes an error

### ISSUE THREAD

**Issue by louieo** [Cameri/nostream#218]
**Describe the bug**
When running ./start within the scripts directory, the startup fails with error "configuration file "/postgresql.conf" contains errors"

**To Reproduce**
cd scripts
./start

**Expected behavior**
Application starts without error.
Resolution is to run the start script from outside the scripts directory eg ./scripts/start

**System:**
 - OS: Ubuntu 22.04
 - Platform: docker
 - Version: 1.22.4

**Comment by Giszmo** [comment]
can you share your /postgresql.conf? What did you change?

**Comment by louieo** [comment]
I didn't make any change to postgresql.conf. I just pulled the latest using git, but when I tried to run the start script, I was within the scripts folder. I think it's a red herring referring to postgresql.conf. Once I "cd .. " back to outside scripts dir, the command ". ./scripts/start" worked fine
