### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by taurusites** [Cameri/nostream#232]
**Multiple subscription Issue**
To be honest I am not sure whether this is a bug or this is by design, but if I have subscribed twice with the same pubkey while running nostream in a paid configuration I get a NOTICE: subscription rejected 

**To Reproduce**

Open https://nostr.ownbtc.online and make payment twice with the same pubkey
Open https://snort.social and open the dev tools view the console and the notice should show in a short while.

**Expected behavior**
My assumption is that multiple subscriptions should be allowed, and even the NOTICE seems to suggest that.

**Screenshots**
![nostreamsubscriptionrejected](https://user-images.githubusercontent.com/13499006/221392377-f07b3492-5fa4-4d8a-a5c5-29ee0c377760.png)

**System (please complete the following information):**
 - OS: Windows !!
 - Platform: docker, standalone
 - Version: 1.22.6

**Additional context**
I have also added the pubkey to the white list section of settings.yml

**Comment by taurusites** [comment]
![subscriptionerror](https://user-images.githubusercontent.com/13499006/221396008-ff35844b-23bc-4239-a2e1-f0863941ecaa.png)
I think this screen cap might be clearer

**Comment by Cameri** [comment]
@taurusites which client are you using? looks like your client opens subscriptions over and over and does not close them

**Comment by Cameri** [comment]
@taurusites Paying a relay or not does not affect subscriptions, it only affects your ability to publish/post to that relay.
The issue you see above is a client opening too many subscriptions and then forgetting about them.

**Comment by taurusites** [comment]
This may possibly be it because it also happens with eden.nostr.land where I paid 2 subscriptions by mistake however the subscription issue also shows up in iris.to. Could it be the same issue there as well ?
![iriserror](https://user-images.githubusercontent.com/13499006/221909152-c864deb5-edaa-4857-ae04-cc41344891bf.png)

**Comment by Cameri** [comment]
If you paid twice on Eden I can refund you for one. However you are still confused about what a paid relay means: it has nothing to do with subscriptions, paying for it only allows you to publish to it.

**Comment by Cameri** [comment]
Multiple subscriptions are allowed. Please read CONFIGURATION.md and look for `limits.client.subscription.maxSubscriptions` on information how to change this setting for your own relay.

**Comment by taurusites** [comment]
Thank you for your patience with me.
