### ISSUE TITLE
Adding Railway Script

### ISSUE THREAD

**Issue by saranshisatgit** [Cameri/nostream#27]
Deployment template for the railway.app

**Comment by saranshisatgit** [comment]
Working on setting it up so that community can benefit from this template!

**Comment by saranshisatgit** [comment]
So, I need to work on the configuration part. That will be merged as config.toml , I am planning to  add this in the config 


1. Build and Dependency Setup 
2. DB and Check Migration if it exists 
3. Then run the DB migration 
4. Setup the domain (usually these services provide domain mapping that is temporary )
5. Test if the nostr relay is up and live. (Probably running by tests)

**Comment by Cameri** [comment]
Perhaps the `docker-compose.yml` can serve as inspiration for this.

**Comment by Cameri** [comment]
Completed in #49
