### ISSUE TITLE
[REQUEST] Official dockerhub image

### ISSUE THREAD

**Issue by PatrickGeyer** [Cameri/nostream#322]
**Pledge**
Would pledge $25 to see an official and maintained dockerhub image of nostream.
Should be possible to pull image and get it running using just the pulled image and environment variables if you want to overwrite default certificate etc. Should work for local testing and prod.

![Screenshot 2023-05-27 at 13 38 50](https://github.com/Cameri/nostream/assets/5664617/3420caf2-1881-4e95-92e8-62db08643f6e)

**Comment by Cameri** [comment]
We are pushing images to ghcr here: https://github.com/Cameri/nostream/pkgs/container/nostream

Is this still needed?
