### ISSUE TITLE
[BUG] changing port doesn't work

### ISSUE THREAD

**Issue by ralyodio** [Cameri/nostream#329]
I added RELAY_PORT=9421 to my .env. It seems to be ignored.

What port do I tell nginx to proxy to?

**Comment by Cameri** [comment]
Proxy to port 8008 or make changes in the `docker-compose.yml` file. Please re-open the issue if you still need help.

**Comment by ralyodio** [comment]
had to hack up docker-compose.yml would be better to read from .env for exposed port.

**Comment by Cameri** [comment]
> had to hack up docker-compose.yml would be better to read from .env for exposed port.

Agreed. I'll make it so it can be overridden by the env file.
